version: '3.8'
services:
  nestapp:
    container_name: nestapp
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=bunlung
      - POSTGRES_PASSWORD=5087
      - POSTGRES_DB=ecommerce_db
    volumes:
      - pgdata:/var/lib/postgresql/data     
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL=bellsau5087@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=50875087     
    ports:
      - 80:80    
    depends_on:
      - db    
volumes:
  pgdata: